---
abstract: 'Rails like String Inflector'
author:
  - 'Ryuta Kamizono <kamipo@gmail.com>'
build_requires:
  Test::More: 0
distribution_type: module
generated_by: 'Module::Install version 0.79'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: autobox-String-Inflector
no_index:
  directory:
    - inc
    - t
requires:
  Lingua::EN::Inflect::Number: 0
  String::CamelCase: 0
  autobox: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.01
